#pragma once

#ifndef _DEVICEINFO_h
#define _DEVICEINFO_h

#define LEFT_CONTROLLER 0
#define RIGHT_CONTROLLER 1

#define ACCESS_CODE1 213
#define ACCESS_CODE2 194

#define PROTOCOL_VERSION_MAJOR 1
#define PROTOCOL_VERSION_MINOR 0
#define PROTOCOL_VERSION_PATCH 0

#define FIRMWARE_VERSION_MAJOR 0
#define FIRMWARE_VERSION_MINOR 2
#define FIRMWARE_VERSION_PATCH 0

#define DEVICE_TYPE RIGHT_CONTROLLER

#endif